import type { Metadata } from 'next';
import Navbar from '@/components/layouts/navbar';
import { geistMono, geistSans, outfit } from '@/app/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable}`}
    >
      <body>
        {children}
      </body>
    </html>
  );
}
